server:
  port: 80

#Eureka配置
eureka:
  client:
    #不向Eureka注册自己
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka-server-01:7001/eureka/,http://eureka-server-02:7002/eureka/,http://eureka-server-03:7003/eureka/