server:
  port: 10010

spring:
  application:
    name: springcloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LostRed/springcloud-example-config.git